export const GET_GAME_DATA_REQUEST = "GET_GAME_DATA_REQUEST"
export const GET_GAME_DATA_SUCCESS = 'GET_GAME_DATA_SUCCESS';
export const GET_GAME_DATA_ERROR = 'GET_GAME_DATA_ERROR';
//export const PUT_IS_LOADING = 'PUT_IS_LOADING';
export const POST_GAME_TO_FIRESTORE_REQUEST = "POST_GAME_TO_FIRESTORE_REQUEST"
export const POST_GAME_TO_FIRESTORE_SUCCESS = "POST_GAME_TO_FIRESTORE_SUCCESS"
export const POST_GAME_TO_FIRESTORE_ERROR = "POST_GAME_TO_FIRESTORE_ERROR"

